run:
  tests: true
  timeout: 5m

output:
  print-issued-lines: true


linters-settings:
  govet:
    enable:
      - 'shadow'
  dupl:
    threshold: 100
  goconst:
    min-len: 8
    min-occurrences: 3
  gocyclo:
    min-complexity: 20
  gocritic:
    disabled-checks:
      - ifElseChain
  depguard:
    rules:
      main:
        deny:
          - pkg: github.com/pkg/errors
            desc: "use fmt.Errorf or errors.New"
          - pkg: github.com/stretchr/testify
            desc: "use fmt.Errorf or errors.New"
          - pkg: github.com/alecthomas/errors
            desc: "use fmt.Errorf or errors.New"

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-use-default: false